services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - mern
    depends_on:
      - backend
      
  backend:
    build: ./api
    ports:
      - "5000:5000"
    networks:
      - mern
    env_file:
      - ./api/.env

networks:
  mern:
    driver: bridge

